# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baza_wydatkow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField()),
                ('miesiac', models.IntegerField()),
                ('tydzien', models.IntegerField()),
                ('dzien', models.IntegerField()),
                ('typ', models.CharField(max_length=128)),
                ('nazwa', models.CharField(max_length=128)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
                ('komentarz', models.CharField(max_length=256)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
