# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza_wydatkow',
            name='data_utworzenia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
