# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0002_auto_20160325_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza_wydatkow',
            name='okres',
            field=models.CharField(default='032016', max_length=8),
            preserve_default=False,
        ),
    ]
