# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0004_remove_baza_wydatkow_nazwa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ_wydatku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_wydatku', models.CharField(max_length=128)),
            ],
        ),
    ]
