# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0005_typ_wydatku'),
    ]

    operations = [
        migrations.AddField(
            model_name='typ_wydatku',
            name='nazwa_skrocona',
            field=models.CharField(default='puste', max_length=128),
            preserve_default=False,
        ),
    ]
