# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0007_lista_okresow'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_okresow',
            name='koniec_okresu',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lista_okresow',
            name='poczatek_okresu',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
