# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0012_auto_20160624_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_okresow',
            name='koniec_okresu',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lista_okresow',
            name='poczatek_okresu',
            field=models.DateTimeField(blank=True),
        ),
    ]
